#!/bin/bash

if [[ $# -lt 2 ]]; then
  echo "usage:   ./script/update-all LIBNAME ARCHIVE_DIR"
  echo "example: ./script/update-all cure archive"
  exit 1
fi

libname=$1
archive_dir=$2

for i in $(tac versions/$libname); do
  # ./script/download --output-dir $archive_dir $i
  ./script/update --skip $archive_dir/$i
done
# tac versions/$libname |
#   xargs -n 1 ./script/download --output-dir $archive_dir
